# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CimzMLParse <- function(xml_path) {
    .Call(`_rMSI_CimzMLParse`, xml_path)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib rMSI, .registration = TRUE
NULL

#' MergeMassAxis.
#' 
#' Merges two mass axis in a single one using an apropiate bin size.
#' The resulting mass axis will display a bin size equal to the minimum of two supplied vectors. 
#' The bin size is calculated relative to the m/z for better accuracy.
#' The resulting mass axis range is calculated using the common range between the two mass axis.
#' If there is no overlao between the two mass axis range an error will be raised.
#' 
#' @param mz1 the first mass axis to merge.
#' @param mz2 the second mass axis to merge.
#' 
#' @return a common mass axis that represents mz1 and mz1 accurately.
#' @export
#' 
MergeMassAxis <- function(mz1, mz2) {
    .Call(`_rMSI_MergeMassAxis`, mz1, mz2)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib rMSI, .registration = TRUE
NULL

ReduceDataPointsC <- function(mass, intensity, massMin, massMax, npoints) {
    .Call(`_rMSI_ReduceDataPointsC`, mass, intensity, massMin, massMax, npoints)
}

